theme : minima
header_pages:
  - about.md
  - contact.md
  - posts.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
title: "Paper Reviews on Neuroscience"
description: "Academic blog reviewing papers in computational psychiatry, neuroeconomics, and bioinformatics"
author: "Rayeed Al Mutakabbir"
